apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-configmap
data:
  ELASTIC_APM_ENVIRONMENT: "prod"
  ELASTIC_APM_SECRET_TOKEN: "t2MsG7UEb5UpCY0mF1"
  ELASTIC_APM_SERVER_URL: "https://fraud-detection.apm.southamerica-east1.gcp.elastic-cloud.com"
  CLOUD_ID: "FraudDetection:c291dGhhbWVyaWNhLWVhc3QxLmdjcC5lbGFzdGljLWNsb3VkLmNvbSQzNzkxNTVkOTMyZTM0NDc2YWFkNTZhMzNmYTQ2YjBkMiQ5NGE1MDc1NWFmYjM0NmNmODIyYzNiZTk2YjRhMjZjNA=="
  CLOUD_AUTH: "elastic:QQAm4gtJ13Rn3DZbxIl3oOv4"  
  CLOUD_PASSWORD: "QQAm4gtJ13Rn3DZbxIl3oOv4"